# -*- coding: utf-8 -*-
"""Advertising.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kcSVvEvVsANAxB0NtxKEw5iVIqYcXl5b
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

#Importar Dataset
import io
df=pd.read_csv("Advertising.csv", index_col=0)
df.head()

import statsmodels.formula.api as smf

x=df['TV']
y=df['sales']

est=smf.ols(formula="y~x", data=df).fit()
print(est.summary().tables[1])

#Regresion entre periodico y ventas
z=df['newspaper']

est=smf.ols(formula="y~z", data=df).fit()
print(est.summary().tables[1])

w=df['radio']

est=smf.ols(formula="y~x+w+z", data=df).fit()
print(est.summary().tables[1])