# -*- coding: utf-8 -*-
"""Cap3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QWonORnDTYW2rIoHN-pNmS1zX0FjHHzz
"""

import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.linear_model import LinearRegression

from google.colab import files
upload=files.upload()

import io
auto=pd.read_csv("Auto.csv")
auto.head()

x=pd.to_numeric(auto["horsepower"], errors='coerce')
y=auto["mpg"]

regr=LinearRegression()

model=regr.fit(x,y)

auto["pred"]=model.predict(x)
auto["resid"]=auto["mpg"]-auto["pred"]

sns.regplot(auto["pred"], auto["resid"], lowess=True)