# -*- coding: utf-8 -*-
"""VIF.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14JBq5h2ra3u0BsI3xAmNRHWHfZ7yrsEW
"""

from google.colab import files
uploaded=files.upload()

import io
import pandas as pd
import numpy as np
from statsmodels.stats.outliers_influence import variance_inflation_factor
from patsy import dmatrices

credit=pd.read_csv("Credit.csv").dropna()._get_numeric_data()

y,x=dmatrices("Balance~Age+Rating+Limit", credit, return_type="dataframe")

cols=x.shape[1]
vif=pd.DataFrame()

vif["features"]=x.columns
vif["VIF Factor"]=[variance_inflation_factor(x.values,i) for i in range(cols)]

vif.index=np.arange(1, len(vif)+1)

vif.round(2)